### ISSUE TITLE
ERROR with GCC 4.4.7 on CentOS 6.5

### ISSUE THREAD

**Issue by quangtu89** [Tencent/rapidjson#2082]
I add rapidjson to include project and compile with gcc 4.4.7 on centos 6.5

`/root/server/src/../include/rapidjson/document.h:1902: error: ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::GenericDocument(const rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>&) [with Encoding = rapidjson::UTF8<char>, Allocator = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, StackAllocator = rapidjson::CrtAllocator]’ is private
`
